### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by tacman** [StenopePHP/Stenope#174]
Currently composer.json only allows up to Symfony 6, but Symfony 7 will be out in less than 2 months.

This may be released to #173 , since asset() and importmap() have changes need to be reviewed here.  

Symfony 4.4 will become unsupported next month, if it makes it easier to fix issues, I'd suggest dropping 4.4 and PHP < 8.1.

**Comment by tacman** [comment]
Thank you for adding Symfony 7 support.  Can you please release this as 1.0?  git handles 0.x releases differently, so ^0.8 does _not_ automatically load 0.9 when doing a composer update.

**Comment by ogizanagi** [comment]
> Thank you for adding Symfony 7 support. Can you please release this as 1.0? git handles 0.x releases differently, so ^0.8 does _not_ automatically load 0.9 when doing a composer update.

That was on purpose indeed. But we might consider bumping it to 1.0.0 in next release.
